---
- hosts: all
  sudo: yes
  roles:
    - role: db
    - role: redis
      redis_ppa:
      redis_enabled: yes
      redis_dbfilename: redis.rdb
      redis_db_dir: /var/db/redis
      redis_maxmemory_policy: allkeys-lru
    - role: elasticsearch
      elasticsearch_timezone: "Etc/UTC"
      elasticsearch_plugins:
          - name: 'mobz/elasticsearch-head'
    - role: web
      tags: ["web"]
    - role: elasticsearch_index
  vars:
    atlas_django_listen_addr: 0.0.0.0 # So it can listen to requests from non-localhost
    atlas_db_user: atlas
    atlas_db_password: atlas
    atlas_db_name: atlas
    atlas_db_host: 127.0.0.1
    atlas_db_port: 3306
    atlas_prefix: /srv/atlas
    atlas_static_image_path: /var/db/images/
    atlas_vagrant: true
    atlas_dev: false

