---
- hosts: all
  sudo: yes
  roles:
    - role: db
    - role: redis
      redis_ppa:
      redis_enabled: yes
      redis_dbfilename: redis.rdb
      redis_db_dir: /var/db/redis
      redis_maxmemory_policy: allkeys-lru
    - role: elasticsearch
      elasticsearch_timezone: "Etc/UTC"
      elasticsearch_plugins:
          - name: 'mobz/elasticsearch-head'
    - role: web
      tags: ["web"]
    - role: elasticsearch_index
