---
- hosts: all
  gather_facts: false
  roles:
    - {role: db}
    - {role: web}
  vars:
    atlas_db_user: atlas
    atlas_db_password: atlas
    atlas_db_host: 127.0.0.1
    atlas_db_port: 3306
    atlas_prefix: /srv/atlas

