---
- hosts: all
  sudo: yes
  pre_tasks:
    - include: check_git_synced.yml
      sudo: no
      when: atlas_environment != 'dev'
  roles:
    - role: db
      when: atlas_environment == 'dev'
    - role: redis
      redis_ppa:
      redis_enabled: yes
      redis_dbfilename: redis.rdb
      redis_db_dir: /var/db/redis
      redis_maxmemory_policy: allkeys-lru
      when: atlas_environment == 'dev'
    - role: elasticsearch
      elasticsearch_version: 1.7.6
      elasticsearch_timezone: "Etc/UTC"
      elasticsearch_plugins:
          - name: 'mobz/elasticsearch-head'
    - role: web
    - role: elasticsearch_index
