- name: Generate search index
  django_manage: >
      command=index_questions
      app_path={{atlas_prefix}}/django_files/
      virtualenv={{atlas_prefix}}/env/
  tags:
      - elasticsearch_index
