- name: import atlas db
  mysql_db: name={{atlas_db_name}} state=import target={{atlas_db_import_location}}
  notify:
      - workaround1 for mate bug
      - workaround2 for mate bug
      - workaround for missing sudan ranking data
      - add flag to specify originally included countries
      - django syncdb
      - Generate search index
# Quick fixes to the data
- include: hacks.yml
