- name: import atlas db
  mysql_db: name={{atlas_db_name}} state=import target=/vagrant_shared/atlas_dump.sql.bz2
  notify:
      - workaround1 for mate bug
      - workaround2 for mate bug
      - workaround2 for mate bug
      - workaround for missing sudan ranking data
      - django syncdb
# Quick fixes to the data
- include: hacks.yml
