---
- name: install system packages
  apt: pkg={{item}} state=present
  with_items: system_packages
- name: install virtualenv
  pip: name=virtualenv
- name: create srv dir
  file: dest={{prefix}} owner=vagrant group=vagrant state=directory recurse=yes
- name: get code
  git: repo=git@github.com:cid-harvard/atlas-economic-complexity.git
       dest={{prefix}}
       version=master

# TODO: Install pip packages manually for now to avoid installing numpy, it
# takes forever. Also django version not specified in requirements.txt
#- name: install atlas python requirements
#  pip: requirements={{prefix}}/requirements.txt virtualenv={{prefix}}/env/
- name: install atlas python requirements
  pip: name={{item}} virtualenv={{prefix}}/env/
  with_items:
    - Django==1.4.5
    - MySQL-python
    - django-redis
    - msgpack-python
    - pycrypto
- name: generate django settings
  template: src=settings_local.py dest={{prefix}}/django_files/atlas/
- name: Set permissions to django directory
  file: owner={{webuser}} recurse=yes dest={{prefix}}

#TODO: Doing this via shell for now because django_manage doesn't let you pass
#a listen ip to runserver. Don't do this in production
#- name: Run server
#  django_manage: >
#      command=runserver
#      app_path={{prefix}}/django_files/
#      virtualenv={{prefix}}/env/

#- name: run django server
#  shell: ls; {{prefix}}/env/bin/python {{prefix}}/django_files/manage.py runserver --pythonpath={{prefix}}/django_files/ 0.0.0.0:8000
