---
system_packages:
    - language-pack-en
    - git
    - python2.7
    - python-pip
    - python-passlib
    - libmysqlclient-dev
    - python-dev
    - libffi-dev
    - libcairo2-dev
    - nginx
    - phantomjs
    - supervisor
    - uwsgi
    - uwsgi-plugin-python
    - cssmin
    - nodejs-legacy
    - npm
